In [55]:
# Import libraries
import pandas as pd
from pulp import *

__*Low Season*__

In [56]:
# Load the dataset and import it into dataframe.
# Determine number of work weeks 
week = ["Mon", "Tue", "Wen", "Thu", "Fri", "Sat", "Sun"]

file_path = '../../Files/fau_airlines_shifts.csv'
df_low_season = pd.read_csv(file_path, nrows=18)

In [57]:
# Replace all X values with 1 and NAN with 0
df_low_season = df_low_season.fillna(0).applymap(lambda x: 1 if x == "X" else x)

C:\Users\basse\AppData\Local\Temp\ipykernel_30044\1284911028.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_low_season = df_low_season.fillna(0).applymap(lambda x: 1 if x == "X" else x)

In [58]:
# DataSet for low season
df_low_season

,Time Windows,Shift 1,Shift 2,Shift 3,Avg_Passenger_No_1,Avg_Passenger_No_2,Avg_Passenger_No_3,Avg_Passenger_No_4,Avg_Passenger_No_5,Avg_Passenger_No_6,Avg_Passenger_No_7
0,05:00 - 06:00,1,0,0,112,3,0,158,142,12,0
1,06:00 - 07:00,1,0,0,247,5,0,223,212,178,0
2,07:00 - 08:00,1,0,0,38,11,8,54,45,112,8
3,08:00 - 09:00,1,0,0,79,12,15,32,23,36,15
4,9:00 - 10:00,1,0,0,113,14,22,268,286,231,22
5,10:00 - 11:00,1,0,0,57,14,27,245,234,199,27
6,11:00 - 12:00,0,1,0,17,15,28,89,67,200,28
7,12:00 - 13:00,0,1,0,68,19,0,22,34,57,0
8,13:00 - 14:00,0,1,0,5,7,0,25,54,54,0
9,14:00 - 15:00,0,1,0,18,2,0,118,167,167,0
10,15:00 - 16:00,0,1,0,25,45,0,258,265,144,0
11,16:00 -17:00,0,1,0,118,78,47,189,168,168,47
12,17:00 - 18:00,0,0,1,258,126,113,24,43,44,113
13,18:00 - 19:00,0,0,1,189,56,23,189,46,64,23
14,19:00 - 20:00,0,0,1,24,42,28,24,27,72,28
15,20:00-21:00,0,0,1,5,12,0,48,29,49,0
16,21:00-22:00,0,0,1,1,0,0,11,40,40,0
17,22:00-23:00,0,0,1,0,0,0,5,59,50,0

In [59]:
# Fetch the average passengers columns and put it in an array 
avg_passenger_no_columns = []
for day_of_week in range(1, 8):
    avg_passenger_no_columns.append(f'Avg_Passenger_No_{day_of_week}')
    
avg_passenger_no_columns

['Avg_Passenger_No_1',
 'Avg_Passenger_No_2',
 'Avg_Passenger_No_3',
 'Avg_Passenger_No_4',
 'Avg_Passenger_No_5',
 'Avg_Passenger_No_6',
 'Avg_Passenger_No_7']

In [60]:
# Fetch the Shifts column
shifts = df_low_season.drop(columns=avg_passenger_no_columns + ["Time Windows"]).values
shifts

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=int64)

In [61]:
# Read the rest of the data from the the csv file

# Number of shifts
shift_num = shifts.shape[1]
print("shift_num:", shift_num)

# Number of time windows
time_windows = shifts.shape[0]
print("time_windows:", time_windows)

# Number of customers measured per time window
avg_passenger_no_low = df_low_season[avg_passenger_no_columns].values
print("avg_passenger_no_low:\n", avg_passenger_no_low)

# Service level during the low Season
avg_processing_time = 2.4  # in minutes
service_level_low = (1 / int(60 / 2.4))
#service_level_low = int(60 / 2.4)
print("service_level_low:", service_level_low)

shift_num: 3
time_windows: 18
avg_passenger_no_low:
 [[112   3   0 158 142  12   0]
 [247   5   0 223 212 178   0]
 [ 38  11   8  54  45 112   8]
 [ 79  12  15  32  23  36  15]
 [113  14  22 268 286 231  22]
 [ 57  14  27 245 234 199  27]
 [ 17  15  28  89  67 200  28]
 [ 68  19   0  22  34  57   0]
 [  5   7   0  25  54  54   0]
 [ 18   2   0 118 167 167   0]
 [ 25  45   0 258 265 144   0]
 [118  78  47 189 168 168  47]
 [258 126 113  24  43  44 113]
 [189  56  23 189  46  64  23]
 [ 24  42  28  24  27  72  28]
 [  5  12   0  48  29  49   0]
 [  1   0   0  11  40  40   0]
 [  0   0   0   5  59  50   0]]
service_level_low: 0.04

In [62]:
# Determine the decision variable low Season
# final goal is to find the optimal number of workers for each time slot of each day
num_workers_indexes = []
for day_of_week in range(0,7):
  for shift_index in range(shift_num):
    num_workers_indexes.append(f'{day_of_week}_{shift_index}')
    
num_workers = LpVariable.dicts("num_workers", num_workers_indexes, cat="Integer")
print(num_workers)

{'0_0': num_workers_0_0, '0_1': num_workers_0_1, '0_2': num_workers_0_2, '1_0': num_workers_1_0, '1_1': num_workers_1_1, '1_2': num_workers_1_2, '2_0': num_workers_2_0, '2_1': num_workers_2_1, '2_2': num_workers_2_2, '3_0': num_workers_3_0, '3_1': num_workers_3_1, '3_2': num_workers_3_2, '4_0': num_workers_4_0, '4_1': num_workers_4_1, '4_2': num_workers_4_2, '5_0': num_workers_5_0, '5_1': num_workers_5_1, '5_2': num_workers_5_2, '6_0': num_workers_6_0, '6_1': num_workers_6_1, '6_2': num_workers_6_2}

In [63]:
# Create LP problem for low Season
prob1 = LpProblem("scheduling_workers", LpMinimize)

In [64]:
# Add constraints to the problem for low Season
avg_passenger_no_low
print(avg_passenger_no_low)
for day_of_week in range(7):
  for t in range(time_windows):
    print("avg_passenger_no:", avg_passenger_no_low[t][day_of_week])
    prob1 += lpSum([shifts[t, j] * num_workers[f'{day_of_week}_{j}'] for j in range(shift_num)]) >= avg_passenger_no_low[t][day_of_week] * service_level_low

[[112   3   0 158 142  12   0]
 [247   5   0 223 212 178   0]
 [ 38  11   8  54  45 112   8]
 [ 79  12  15  32  23  36  15]
 [113  14  22 268 286 231  22]
 [ 57  14  27 245 234 199  27]
 [ 17  15  28  89  67 200  28]
 [ 68  19   0  22  34  57   0]
 [  5   7   0  25  54  54   0]
 [ 18   2   0 118 167 167   0]
 [ 25  45   0 258 265 144   0]
 [118  78  47 189 168 168  47]
 [258 126 113  24  43  44 113]
 [189  56  23 189  46  64  23]
 [ 24  42  28  24  27  72  28]
 [  5  12   0  48  29  49   0]
 [  1   0   0  11  40  40   0]
 [  0   0   0   5  59  50   0]]
avg_passenger_no: 112
avg_passenger_no: 247
avg_passenger_no: 38
avg_passenger_no: 79
avg_passenger_no: 113
avg_passenger_no: 57
avg_passenger_no: 17
avg_passenger_no: 68
avg_passenger_no: 5
avg_passenger_no: 18
avg_passenger_no: 25
avg_passenger_no: 118
avg_passenger_no: 258
avg_passenger_no: 189
avg_passenger_no: 24
avg_passenger_no: 5
avg_passenger_no: 1
avg_passenger_no: 0
avg_passenger_no: 3
avg_passenger_no: 5
avg_passenger_no: 11
avg_passenger_no: 12
avg_passenger_no: 14
avg_passenger_no: 14
avg_passenger_no: 15
avg_passenger_no: 19
avg_passenger_no: 7
avg_passenger_no: 2
avg_passenger_no: 45
avg_passenger_no: 78
avg_passenger_no: 126
avg_passenger_no: 56
avg_passenger_no: 42
avg_passenger_no: 12
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 8
avg_passenger_no: 15
avg_passenger_no: 22
avg_passenger_no: 27
avg_passenger_no: 28
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 47
avg_passenger_no: 113
avg_passenger_no: 23
avg_passenger_no: 28
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 158
avg_passenger_no: 223
avg_passenger_no: 54
avg_passenger_no: 32
avg_passenger_no: 268
avg_passenger_no: 245
avg_passenger_no: 89
avg_passenger_no: 22
avg_passenger_no: 25
avg_passenger_no: 118
avg_passenger_no: 258
avg_passenger_no: 189
avg_passenger_no: 24
avg_passenger_no: 189
avg_passenger_no: 24
avg_passenger_no: 48
avg_passenger_no: 11
avg_passenger_no: 5
avg_passenger_no: 142
avg_passenger_no: 212
avg_passenger_no: 45
avg_passenger_no: 23
avg_passenger_no: 286
avg_passenger_no: 234
avg_passenger_no: 67
avg_passenger_no: 34
avg_passenger_no: 54
avg_passenger_no: 167
avg_passenger_no: 265
avg_passenger_no: 168
avg_passenger_no: 43
avg_passenger_no: 46
avg_passenger_no: 27
avg_passenger_no: 29
avg_passenger_no: 40
avg_passenger_no: 59
avg_passenger_no: 12
avg_passenger_no: 178
avg_passenger_no: 112
avg_passenger_no: 36
avg_passenger_no: 231
avg_passenger_no: 199
avg_passenger_no: 200
avg_passenger_no: 57
avg_passenger_no: 54
avg_passenger_no: 167
avg_passenger_no: 144
avg_passenger_no: 168
avg_passenger_no: 44
avg_passenger_no: 64
avg_passenger_no: 72
avg_passenger_no: 49
avg_passenger_no: 40
avg_passenger_no: 50
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 8
avg_passenger_no: 15
avg_passenger_no: 22
avg_passenger_no: 27
avg_passenger_no: 28
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 47
avg_passenger_no: 113
avg_passenger_no: 23
avg_passenger_no: 28
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 0

In [65]:
# Solve the problem for low season
prob1.solve()
print("Status:", LpStatus[prob1.status])

Status: Optimal

In [66]:
# Print the results for low season
for index in num_workers:
  index_parts = index.split('_')
  day_of_week = int(index_parts[0])
  day = week[day_of_week]
  shift = index_parts[1]
  print(f"The number of workers needed for day {day} shift {shift} is {int(num_workers[index].value())} workers")

The number of workers needed for day Mon shift 0 is 10 workers
The number of workers needed for day Mon shift 1 is 5 workers
The number of workers needed for day Mon shift 2 is 11 workers
The number of workers needed for day Tue shift 0 is 1 workers
The number of workers needed for day Tue shift 1 is 4 workers
The number of workers needed for day Tue shift 2 is 6 workers
The number of workers needed for day Wen shift 0 is 2 workers
The number of workers needed for day Wen shift 1 is 2 workers
The number of workers needed for day Wen shift 2 is 5 workers
The number of workers needed for day Thu shift 0 is 11 workers
The number of workers needed for day Thu shift 1 is 11 workers
The number of workers needed for day Thu shift 2 is 8 workers
The number of workers needed for day Fri shift 0 is 12 workers
The number of workers needed for day Fri shift 1 is 11 workers
The number of workers needed for day Fri shift 2 is 3 workers
The number of workers needed for day Sat shift 0 is 10 workers
The number of workers needed for day Sat shift 1 is 8 workers
The number of workers needed for day Sat shift 2 is 3 workers
The number of workers needed for day Sun shift 0 is 2 workers
The number of workers needed for day Sun shift 1 is 2 workers
The number of workers needed for day Sun shift 2 is 5 workers

__*High Season*__

In [67]:
# Create a copy of the dataset
df_high_season = df_low_season.copy()

# During the high season, especially throughout the winter and summer breaks, the average number of passengers doubles
df_high_season[avg_passenger_no_columns] *= 2

# Set Wednesdays' values equal to Mondays' values
# "Wednesdays are as busy as Mondays"
df_high_season['Avg_Passenger_No_3'] = df_high_season['Avg_Passenger_No_1']

# Set Saturdays' values equal to Sundays' values
# "Sundays are as busy as Saturdays"
df_high_season['Avg_Passenger_No_7'] = df_high_season['Avg_Passenger_No_6']

In [68]:
# DataSet for high season
df_high_season

,Time Windows,Shift 1,Shift 2,Shift 3,Avg_Passenger_No_1,Avg_Passenger_No_2,Avg_Passenger_No_3,Avg_Passenger_No_4,Avg_Passenger_No_5,Avg_Passenger_No_6,Avg_Passenger_No_7
0,05:00 - 06:00,1,0,0,224,6,224,316,284,24,24
1,06:00 - 07:00,1,0,0,494,10,494,446,424,356,356
2,07:00 - 08:00,1,0,0,76,22,76,108,90,224,224
3,08:00 - 09:00,1,0,0,158,24,158,64,46,72,72
4,9:00 - 10:00,1,0,0,226,28,226,536,572,462,462
5,10:00 - 11:00,1,0,0,114,28,114,490,468,398,398
6,11:00 - 12:00,0,1,0,34,30,34,178,134,400,400
7,12:00 - 13:00,0,1,0,136,38,136,44,68,114,114
8,13:00 - 14:00,0,1,0,10,14,10,50,108,108,108
9,14:00 - 15:00,0,1,0,36,4,36,236,334,334,334
10,15:00 - 16:00,0,1,0,50,90,50,516,530,288,288
11,16:00 -17:00,0,1,0,236,156,236,378,336,336,336
12,17:00 - 18:00,0,0,1,516,252,516,48,86,88,88
13,18:00 - 19:00,0,0,1,378,112,378,378,92,128,128
14,19:00 - 20:00,0,0,1,48,84,48,48,54,144,144
15,20:00-21:00,0,0,1,10,24,10,96,58,98,98
16,21:00-22:00,0,0,1,2,0,2,22,80,80,80
17,22:00-23:00,0,0,1,0,0,0,10,118,100,100

In [69]:
# Number of customers measured per time window high Season
avg_passenger_no_high = df_high_season[avg_passenger_no_columns].values
print("avg_passenger_no_high:\n", avg_passenger_no_high)


# Service level during the high season
service_level_high = 1 / 32
print("service_level_high:", service_level_high)

avg_passenger_no_high:
 [[224   6 224 316 284  24  24]
 [494  10 494 446 424 356 356]
 [ 76  22  76 108  90 224 224]
 [158  24 158  64  46  72  72]
 [226  28 226 536 572 462 462]
 [114  28 114 490 468 398 398]
 [ 34  30  34 178 134 400 400]
 [136  38 136  44  68 114 114]
 [ 10  14  10  50 108 108 108]
 [ 36   4  36 236 334 334 334]
 [ 50  90  50 516 530 288 288]
 [236 156 236 378 336 336 336]
 [516 252 516  48  86  88  88]
 [378 112 378 378  92 128 128]
 [ 48  84  48  48  54 144 144]
 [ 10  24  10  96  58  98  98]
 [  2   0   2  22  80  80  80]
 [  0   0   0  10 118 100 100]]
service_level_high: 0.03125

In [70]:
# Determine the decision variable high Season
# final goal is to find the optimal number of workers for each time slot of each day

num_workers_indexes = []
for day_of_week in range(0,7):
  for shift_index in range(shift_num):
    num_workers_indexes.append(f'{day_of_week}_{shift_index}')
    
num_workers = LpVariable.dicts("num_workers", num_workers_indexes, cat="Integer")
print(num_workers)

{'0_0': num_workers_0_0, '0_1': num_workers_0_1, '0_2': num_workers_0_2, '1_0': num_workers_1_0, '1_1': num_workers_1_1, '1_2': num_workers_1_2, '2_0': num_workers_2_0, '2_1': num_workers_2_1, '2_2': num_workers_2_2, '3_0': num_workers_3_0, '3_1': num_workers_3_1, '3_2': num_workers_3_2, '4_0': num_workers_4_0, '4_1': num_workers_4_1, '4_2': num_workers_4_2, '5_0': num_workers_5_0, '5_1': num_workers_5_1, '5_2': num_workers_5_2, '6_0': num_workers_6_0, '6_1': num_workers_6_1, '6_2': num_workers_6_2}

In [71]:
# Create LP problem for high Season

prob2 = LpProblem("scheduling_workers", LpMinimize)

In [72]:
# Add constraints to the problem for high Season
avg_passenger_no_high
print(avg_passenger_no_high)
for day_of_week in range(7):
  for t in range(time_windows):
    print("avg_passenger_no:", avg_passenger_no_high[t][day_of_week])
    prob2 += lpSum([shifts[t, j] * num_workers[f'{day_of_week}_{j}'] for j in range(shift_num)]) >= avg_passenger_no_high[t][day_of_week] * service_level_high

[[224   6 224 316 284  24  24]
 [494  10 494 446 424 356 356]
 [ 76  22  76 108  90 224 224]
 [158  24 158  64  46  72  72]
 [226  28 226 536 572 462 462]
 [114  28 114 490 468 398 398]
 [ 34  30  34 178 134 400 400]
 [136  38 136  44  68 114 114]
 [ 10  14  10  50 108 108 108]
 [ 36   4  36 236 334 334 334]
 [ 50  90  50 516 530 288 288]
 [236 156 236 378 336 336 336]
 [516 252 516  48  86  88  88]
 [378 112 378 378  92 128 128]
 [ 48  84  48  48  54 144 144]
 [ 10  24  10  96  58  98  98]
 [  2   0   2  22  80  80  80]
 [  0   0   0  10 118 100 100]]
avg_passenger_no: 224
avg_passenger_no: 494
avg_passenger_no: 76
avg_passenger_no: 158
avg_passenger_no: 226
avg_passenger_no: 114
avg_passenger_no: 34
avg_passenger_no: 136
avg_passenger_no: 10
avg_passenger_no: 36
avg_passenger_no: 50
avg_passenger_no: 236
avg_passenger_no: 516
avg_passenger_no: 378
avg_passenger_no: 48
avg_passenger_no: 10
avg_passenger_no: 2
avg_passenger_no: 0
avg_passenger_no: 6
avg_passenger_no: 10
avg_passenger_no: 22
avg_passenger_no: 24
avg_passenger_no: 28
avg_passenger_no: 28
avg_passenger_no: 30
avg_passenger_no: 38
avg_passenger_no: 14
avg_passenger_no: 4
avg_passenger_no: 90
avg_passenger_no: 156
avg_passenger_no: 252
avg_passenger_no: 112
avg_passenger_no: 84
avg_passenger_no: 24
avg_passenger_no: 0
avg_passenger_no: 0
avg_passenger_no: 224
avg_passenger_no: 494
avg_passenger_no: 76
avg_passenger_no: 158
avg_passenger_no: 226
avg_passenger_no: 114
avg_passenger_no: 34
avg_passenger_no: 136
avg_passenger_no: 10
avg_passenger_no: 36
avg_passenger_no: 50
avg_passenger_no: 236
avg_passenger_no: 516
avg_passenger_no: 378
avg_passenger_no: 48
avg_passenger_no: 10
avg_passenger_no: 2
avg_passenger_no: 0
avg_passenger_no: 316
avg_passenger_no: 446
avg_passenger_no: 108
avg_passenger_no: 64
avg_passenger_no: 536
avg_passenger_no: 490
avg_passenger_no: 178
avg_passenger_no: 44
avg_passenger_no: 50
avg_passenger_no: 236
avg_passenger_no: 516
avg_passenger_no: 378
avg_passenger_no: 48
avg_passenger_no: 378
avg_passenger_no: 48
avg_passenger_no: 96
avg_passenger_no: 22
avg_passenger_no: 10
avg_passenger_no: 284
avg_passenger_no: 424
avg_passenger_no: 90
avg_passenger_no: 46
avg_passenger_no: 572
avg_passenger_no: 468
avg_passenger_no: 134
avg_passenger_no: 68
avg_passenger_no: 108
avg_passenger_no: 334
avg_passenger_no: 530
avg_passenger_no: 336
avg_passenger_no: 86
avg_passenger_no: 92
avg_passenger_no: 54
avg_passenger_no: 58
avg_passenger_no: 80
avg_passenger_no: 118
avg_passenger_no: 24
avg_passenger_no: 356
avg_passenger_no: 224
avg_passenger_no: 72
avg_passenger_no: 462
avg_passenger_no: 398
avg_passenger_no: 400
avg_passenger_no: 114
avg_passenger_no: 108
avg_passenger_no: 334
avg_passenger_no: 288
avg_passenger_no: 336
avg_passenger_no: 88
avg_passenger_no: 128
avg_passenger_no: 144
avg_passenger_no: 98
avg_passenger_no: 80
avg_passenger_no: 100
avg_passenger_no: 24
avg_passenger_no: 356
avg_passenger_no: 224
avg_passenger_no: 72
avg_passenger_no: 462
avg_passenger_no: 398
avg_passenger_no: 400
avg_passenger_no: 114
avg_passenger_no: 108
avg_passenger_no: 334
avg_passenger_no: 288
avg_passenger_no: 336
avg_passenger_no: 88
avg_passenger_no: 128
avg_passenger_no: 144
avg_passenger_no: 98
avg_passenger_no: 80
avg_passenger_no: 100

In [73]:
# Solve the problem for high season

prob2.solve()
print("Status:", LpStatus[prob2.status])

Status: Optimal

In [75]:
# Print the results for high season

for index in num_workers:
  index_parts = index.split('_')
  day_of_week = int(index_parts[0])
  day = week[day_of_week]
  shift = index_parts[1]
  print(f"The number of workers needed for day {day} shift {shift} is {int(num_workers[index].value())} workers")

The number of workers needed for day Mon shift 0 is 16 workers
The number of workers needed for day Mon shift 1 is 8 workers
The number of workers needed for day Mon shift 2 is 17 workers
The number of workers needed for day Tue shift 0 is 1 workers
The number of workers needed for day Tue shift 1 is 5 workers
The number of workers needed for day Tue shift 2 is 8 workers
The number of workers needed for day Wen shift 0 is 16 workers
The number of workers needed for day Wen shift 1 is 8 workers
The number of workers needed for day Wen shift 2 is 17 workers
The number of workers needed for day Thu shift 0 is 17 workers
The number of workers needed for day Thu shift 1 is 17 workers
The number of workers needed for day Thu shift 2 is 12 workers
The number of workers needed for day Fri shift 0 is 18 workers
The number of workers needed for day Fri shift 1 is 17 workers
The number of workers needed for day Fri shift 2 is 4 workers
The number of workers needed for day Sat shift 0 is 15 workers
The number of workers needed for day Sat shift 1 is 13 workers
The number of workers needed for day Sat shift 2 is 5 workers
The number of workers needed for day Sun shift 0 is 15 workers
The number of workers needed for day Sun shift 1 is 13 workers
The number of workers needed for day Sun shift 2 is 5 workers